name = "raices"
compatibility_date = "2025-01-10"
compatibility_flags = [ "nodejs_compat" ]

main = ".output/server/index.mjs"

assets = { directory = ".output/public", binding = "ASSETS" }

[build]
command = "pnpm build"

[[d1_databases]]
binding = "DB"
database_name = "raices_db"
database_id = "63800bab-e51a-4c0b-811a-7ee8f72d2b9f"

[observability]
enabled = true
